# Generated by Django 5.0.3 on 2024-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_app", "0006_artworkpagegalleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="artworkpage",
            name="copyright",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                max_length=3,
                verbose_name="Does it have copyright content?",
            ),
        ),
    ]
