# Generated by Django 5.0.3 on 2024-03-18 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_app", "0010_artworkregistrationpage_formfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formfield",
            name="page",
        ),
        migrations.DeleteModel(
            name="ArtworkRegistrationPage",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
    ]
