# Generated by Django 5.0.2 on 2024-02-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('github_url', models.URLField(blank=True, verbose_name='Github URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
