# Generated by Django 5.0.2 on 2024-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_formpage_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
    ]
