# Generated by Django 5.0.2 on 2024-03-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_navigationsettings_twitter_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
    ]
